TaskCRUD creation
LeoGuedex/GerenciadorDeTarefas pull request #17
Opened 2023-07-10 21:33 UTC by braga-gustavo

2023-07-16 12:43 UTC, LeoGuedex requested changes

2023-07-16 12:43 UTC, LeoGuedex commented on src/main/java/leoguedex/com/github/ProjetoGerenciadorDeTarefas/controller/TaskController.java
> +    //TODO: arrumar o "retorno" dos GETS, tanto no service quanto no controller
esse comentario ?

2023-07-16 12:43 UTC, LeoGuedex commented on src/main/java/leoguedex/com/github/ProjetoGerenciadorDeTarefas/controller/TaskController.java
> +    @ResponseStatus(HttpStatus.CREATED)
usar o @RequestMapping ao inves do PostMapping, o controller dos outros já segue esse padrão, podera copiar a lógica, isso se faz para todos os endPoints dessa classe.

2023-07-16 12:43 UTC, LeoGuedex commented on src/main/java/leoguedex/com/github/ProjetoGerenciadorDeTarefas/controller/TaskController.java
> +        URI uri = ServletUriComponentsBuilder.fromCurrentRequest().path("/tasks/{id}")
dar uma linha de espaço entre taskToInsert e uri

2023-07-16 12:43 UTC, LeoGuedex commented on src/main/java/leoguedex/com/github/ProjetoGerenciadorDeTarefas/controller/TaskController.java
> +        return ResponseEntity.created(uri).build();
uma linha de espaço antes do return, para ele ser de clara leitura

2023-07-16 12:43 UTC, LeoGuedex commented on src/main/java/leoguedex/com/github/ProjetoGerenciadorDeTarefas/controller/TaskController.java
> +        return ResponseEntity.ok().body(list);
no metodo "findTask' vc passa o service direto dentro do .ok()
e aqui vc cria uma variavel para depois acionar ela dentro do .body()
decida qual é o seu padrão.

2023-07-16 12:43 UTC, LeoGuedex commented on src/main/java/leoguedex/com/github/ProjetoGerenciadorDeTarefas/model/Task.java
> +        }
Praque esse construtor com varios dados, sendo que não tem nenhuma ação no escopo dele ?

2023-07-16 12:43 UTC, LeoGuedex commented on src/main/java/leoguedex/com/github/ProjetoGerenciadorDeTarefas/model/dto/TaskDTO.java
> +    }
pra que isso, se vc tem o @Data que já fornece o getId ? ele pode ser deletado, não ?

2023-07-16 12:43 UTC, LeoGuedex commented on src/main/java/leoguedex/com/github/ProjetoGerenciadorDeTarefas/service/TaskService.java
> +                + Task.class.getName()));
Isso foi testado ? pq qual 'getName' ele vai retornar, se não existe objeto instanciado ?

2023-07-16 12:43 UTC, LeoGuedex commented on src/main/java/leoguedex/com/github/ProjetoGerenciadorDeTarefas/service/TaskService.java
> +                taskDTO.getEstimatedTime(), taskDTO.getTerm());
isso talvez seja a resposta do construtor que vc criou na classe task, só que lá ele não faz nada.
dica: cria primieiro uma task vazia "new Task()"
em seguida, salva numa variavel, e ai vc vai fazendo os variavel.setDado() de todos os campos, ficará mais limpo, ou então usa o @AllArgsConstructor na classe task, e chame o construtor cheio.

2023-07-16 12:43 UTC, LeoGuedex commented on src/main/java/leoguedex/com/github/ProjetoGerenciadorDeTarefas/service/TaskService.java
> +        return taskRepository.save(taskToUpdate);
linha antes do return

2023-07-16 12:43 UTC, LeoGuedex commented on src/main/java/leoguedex/com/github/ProjetoGerenciadorDeTarefas/service/TaskService.java
> +
remover essa linha

2023-07-16 12:43 UTC, LeoGuedex commented on src/main/java/leoguedex/com/github/ProjetoGerenciadorDeTarefas/service/TaskService.java
> +        }catch (DataIntegratyException exception){
} catch

faltou um espaço

2023-07-17 22:49 UTC, leo-guedes-qubit approved these changes

2023-07-17 22:50 UTC, LeoGuedex approved these changes

2023-07-17 22:50 UTC, merged